### ISSUE TITLE
Typo in readme?

### ISSUE THREAD

**Issue by badcel** [kekyo/ILCompose#3]
From looking at the readme it seems that the return types of `ValueTypeTest` do not match? Is this intended?

**Comment by kekyo** [comment]
Thanks reporting, Exactly! This is a TYPO. I will fix it!

**Comment by kekyo** [comment]
Fixed.

**Comment by badcel** [comment]
The one I meant is still there I think in section [What is this](https://github.com/kekyo/ILCompose/blob/main/README.md#what-is-this).

Sorry for the unspecific report. I'm not at a computer currently.

**Comment by kekyo** [comment]
I didn't check and that was the cause of my failure, so no problem. Thanks!
